server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: ServiceA
          uri: http://localhost:8081
          predicates:
            - Path=/api/servicea/**
          filters:
            - StripPrefix=2